gems:
  - jekyll-seo-tag
title: 'Antoine Lenoir : CONCEPTEUR DÉVELOPPEUR APPLICATIONS WEB MOBILES'
description: 'Antoine Lenoir : CONCEPTEUR DÉVELOPPEUR APPLICATIONS WEB MOBILES'
url: 'http://antoinelenoir.com'
author:
  twitter: antoinelenoir
twitter:
  username: antoinelenoir
